created reusable blogs card
learnhubmkd/app pull request #109
Opened 2024-03-22 09:59 UTC by kire21

- I used the existing blog card component for the blog page (made necessary changes to look like in the design).
- I made the tab component sticky, as well as the blog page layout. 

![Screenshot from 2024-03-22 10-43-37](https://github.com/learnhubmkd/app/assets/58231146/3fcc51ae-b4af-453d-a1f1-b1c401617121)
![Screenshot from 2024-03-22 10-43-48](https://github.com/learnhubmkd/app/assets/58231146/b6c4627c-9d88-4e3d-85d0-4bb7563facc5)

2024-03-22 10:25 UTC, stoimenov95 commented
Hey @kire21, the overall code looks fine to me. I just want to make sure regarding the design - should we put the two sections a bit closer to each other to remove that empty space we have now?
<img width="899" alt="Screenshot 2024-03-22 at 11 20 38" src="https://github.com/learnhubmkd/app/assets/32269810/676cdafc-a055-442d-8d5c-b1a6ad9ba4ee">

2024-03-22 10:38 UTC, kire21 commented
> Hey @kire21, the overall code looks fine to me. I just want to make sure regarding the design - should we put the two sections a bit closer to each other to remove that empty space we have now? <img alt="Screenshot 2024-03-22 at 11 20 38" width="899" src="https://private-user-images.githubusercontent.com/32269810/315973587-676cdafc-a055-442d-8d5c-b1a6ad9ba4ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDM3OTgsIm5iZiI6MTcxMTEwMzQ5OCwicGF0aCI6Ii8zMjI2OTgxMC8zMTU5NzM1ODctNjc2Y2RhZmMtYTA1NS00NDJkLThkNWMtYjFhNmFkOWJhNGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEwMzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNjgyMzFiOTE0NDhiNDBjMjU3OTUyN2RmYjFmOWI3NjE5NzZiOWVlYmY2ZjdhZjg0NGFjMDk1NTcyMDk1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.giha1CetF1uTL3EnSg_5NoQfhRH-JmZ-UtWWIdK7d4g">

Hi @stoimenov95,

We need to set the width for the body or main (ex. 1400px) in global.scss because now the layout is full width. When we set the width this problem will be fixed.

2024-03-22 10:40 UTC, edichoska commented
> > Hey @kire21, the overall code looks fine to me. I just want to make sure regarding the design - should we put the two sections a bit closer to each other to remove that empty space we have now? <img alt="Screenshot 2024-03-22 at 11 20 38" width="899" src="https://private-user-images.githubusercontent.com/32269810/315973587-676cdafc-a055-442d-8d5c-b1a6ad9ba4ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDM3OTgsIm5iZiI6MTcxMTEwMzQ5OCwicGF0aCI6Ii8zMjI2OTgxMC8zMTU5NzM1ODctNjc2Y2RhZmMtYTA1NS00NDJkLThkNWMtYjFhNmFkOWJhNGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEwMzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNjgyMzFiOTE0NDhiNDBjMjU3OTUyN2RmYjFmOWI3NjE5NzZiOWVlYmY2ZjdhZjg0NGFjMDk1NTcyMDk1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.giha1CetF1uTL3EnSg_5NoQfhRH-JmZ-UtWWIdK7d4g">
> 
> Hi @stoimenov95,
> 
> We need to set the width for the body or main (ex. 1400px) in global.scss because now the layout is full width. When we set the width this problem will be fixed.

Can we make the change only in the blogs layout, and adjust there? Meaning add margin-left?

2024-03-22 10:41 UTC, edichoska commented
<img width="1421" alt="Screenshot 2024-03-22 at 11 39 33" src="https://github.com/learnhubmkd/app/assets/105276163/6df3d9ab-741c-421f-9861-4c224f9ad933">
Now depending on which tab we are, it shows beneath it За Нас or Најново. Please remove that.

2024-03-22 11:08 UTC, kire21 commented
> <img alt="Screenshot 2024-03-22 at 11 39 33" width="1421" src="https://private-user-images.githubusercontent.com/105276163/315979307-6df3d9ab-741c-421f-9861-4c224f9ad933.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDUxODAsIm5iZiI6MTcxMTEwNDg4MCwicGF0aCI6Ii8xMDUyNzYxNjMvMzE1OTc5MzA3LTZkZjNkOWFiLTc0MWMtNDIxZi05ODYxLTRjMjI0ZjlhZDkzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxMDU0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmM1ZTFkNDExYjA0YzE0NTllMjZiYWI2MTlmNGYyOTllNDk5YTI2NjBkMmE0MDdiNWY1ODMyZjNlZGUxMGVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WbwnKQKxvdcOGV1PhKfBykK562qz3YLr-awr1L05DWo"> Now depending on which tab we are, it shows beneath it За Нас or Најново. Please remove that.

Is it ok now?

![image](https://github.com/learnhubmkd/app/assets/58231146/c22fd90c-899b-49f5-85c7-f9bde35a11c6)

2024-03-23 12:32 UTC, edichoska approved these changes
💅

2024-03-23 12:35 UTC, stoimenov95 requested changes

2024-03-24 12:22 UTC, edichoska commented on components/module-components/blog-list/BlogList.tsx
> +          Види повеќе <HiArrowLongRight fontSize={22} />
Hmm, lets do that, maybe https://icons.getbootstrap.com/ or they should research and find other acceptable options

2024-03-24 12:23 UTC, edichoska commented on components/module-components/blog-list/BlogList.tsx
> +          Види повеќе <HiArrowLongRight fontSize={22} />
@stoimenov95 lets approve this one, and create tickets for the other things we discussed 🙏

2024-03-25 14:34 UTC, RevanchistX commented
@kire21  Please include ticket number in the pull request name

2024-03-26 13:19 UTC, stoimenov95 requested changes
It looks a lot better now, great job @kire21!
I would only add some more spacing between the blogs section and the footer.

2024-03-26 19:37 UTC, stoimenov95 approved these changes

2024-03-26 19:57 UTC, merged