#67 Create Custom Cursor
learnhubmkd/app pull request #129
Opened 2024-03-28 18:31 UTC by Mikivitkovski

2024-03-29 11:01 UTC, edichoska commented
@kire21  can you please help @Mikivitkovski with resolving these conflicts, so nothing is lost. thanks 🙏

2024-03-29 11:46 UTC, kire21 commented
> @kire21  can you please help @Mikivitkovski with resolving these conflicts, so nothing is lost. thanks 🙏 

OK. I'll be in touch with @Mikivitkovski

2024-03-29 13:16 UTC, stoimenov95 requested changes
I have nothing else to add, except for the class name change.

Kudos to you, @Mikivitkovski, the code is very well structured, optimized, and performant.

However, @edichoska, should we be worried about the site's accessibility?

2024-03-29 13:16 UTC, stoimenov95 commented on components/custom-cursor/customcursor.module.scss
> +.large {
@Mikivitkovski we can name this `.largeCursor`

2024-04-01 19:15 UTC, stoimenov95 commented
@Mikivitkovski did you come up with a compromise with @edichoska to use the `square` icon for the cursor in the blog section?

2024-04-01 21:13 UTC, Mikivitkovski commented
> @Mikivitkovski did you come up with a compromise with @edichoska to use the `square` icon for the cursor in the blog section?

Yes we speak, and she told me to be just arrow, and i send to her more different arrows in cursor to decide how its better look, and she told me to do it like that one in the commit

2024-04-01 23:10 UTC, stoimenov95 approved these changes

2024-04-01 23:11 UTC, merged