#105 - created blogs page layout abd infinite scroll
learnhubmkd/app pull request #132
Opened 2024-04-02 08:34 UTC by kire21

Created:

- infinite scroll folder with two files (InfiniteScroll.tsx and infiniteScroll.module.scss)
- action file (action.tsx)

In the action file, I fetched the data.

2024-04-02 08:41 UTC, kire21 commented
[simplescreenrecorder.webm](https://github.com/learnhubmkd/app/assets/58231146/774d366f-9fef-4ddc-8db5-61da2ace3900)

2024-04-02 19:17 UTC, stoimenov95 commented on components/module-components/blog-list/BlogList.tsx
> +import InfinitieScroll from '../../reusable-components/infinite-scroll/InfinitieScroll';
@kire21 Why not `InfiniteScroll`? 😀

2024-04-02 19:22 UTC, stoimenov95 requested changes
Great job @kire21 🥇 !
We can only rename Infinitie to Infinite, and we can hide the `Loading...` element when there are no more posts left to be loaded.

2024-04-03 08:18 UTC, stoimenov95 approved these changes

2024-04-03 22:29 UTC, merged