#115 setup react query
learnhubmkd/app pull request #160
Opened 2024-04-12 19:54 UTC by ninman27

- Set up React Query's QueryClient and provided it at the top level of the app in the Layout
- Created a custom Hook for fetching data
- Implemented error handling and loading states
- Created a simple component Users folder (Users.tsx)

2024-04-14 11:19 UTC, edichoska submitted a review, later dismissed
@ninman27 can you also include useMutaion?

2024-04-14 11:20 UTC, edichoska commented on components/module-components/users/Users.tsx
> +  if (isLoading) return <div>Loading</div>;
can we display here the global loading component we have?

2024-04-15 22:12 UTC, edichoska commented
@ninman27 I keep running into this error:
![Uploading Screenshot 2024-04-16 at 00.09.56.png…]()

2024-04-16 08:55 UTC, ninman27 commented
@edichoska I can't open the image...

2024-04-16 17:13 UTC, edichoska commented
<img width="778" alt="Screenshot 2024-04-16 at 00 09 56" src="https://github.com/learnhubmkd/app/assets/105276163/e04c89ef-e053-4970-8130-901e854788e3">

2024-04-16 18:46 UTC, stoimenov95 requested changes

2024-04-16 18:46 UTC, stoimenov95 commented on app/getUsers.tsx
> +    const data = response.json();
@ninman27 We can return the response.json directly instead of creating the data variable that is only used once.

2024-04-16 20:15 UTC, stoimenov95 commented
> <img alt="Screenshot 2024-04-16 at 00 09 56" width="778" src="https://private-user-images.githubusercontent.com/105276163/322938640-e04c89ef-e053-4970-8130-901e854788e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyOTg4MzAsIm5iZiI6MTcxMzI5ODUzMCwicGF0aCI6Ii8xMDUyNzYxNjMvMzIyOTM4NjQwLWUwNGM4OWVmLWUwNTMtNDk3MC04MTMwLTkwMWU4NTQ3ODhlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQyMDE1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmNiYzVhMDg4MmU1ZjQ3OGM1ZWZlMWVmNjE0YmFkMzE4MTk3YTVmYzljYTYwY2U2OTQwM2JkMWQwY2M1M2Y2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AsYI9qtctbe2IgcCfM16GogXFnPLNQChKWD2gsXJoSk">

I don't experience this problem...

2024-04-16 20:16 UTC, stoimenov95 requested changes
Except for some unnecessary variables, everything else looks awesome @ninman27, great job!

2024-04-17 16:12 UTC, stoimenov95 approved these changes
🥳

2024-04-17 19:35 UTC, merged