#123 integrate cloudfalre turnstile re captcha
learnhubmkd/app pull request #162
Opened 2024-04-12 21:05 UTC by Mikivitkovski

2024-04-15 23:11 UTC, edichoska reviewed
@Mikivitkovski we should be sending the token from the captcha to the backend.

2024-04-15 23:18 UTC, Mikivitkovski commented
> @Mikivitkovski we should be sending the token from the captcha to the backend.

Please check i think is resolved now

2024-04-16 20:21 UTC, stoimenov95 requested changes
<img width="1078" alt="Screenshot 2024-04-16 at 22 20 17" src="https://github.com/learnhubmkd/app/assets/32269810/e1cc38a2-dc71-4475-8281-a46ea6d0a96f">
@Mikivitkovski please build the code and make sure we don't have any errors, then make another request for a review.

2024-04-16 20:21 UTC, stoimenov95 commented on components/reusable-components/newsletter/Newsletter.tsx
> +const handleCaptchaSuccess = () => {};
@Mikivitkovski why are these empty functions?

2024-04-21 18:51 UTC, edichoska approved these changes

2024-04-21 18:54 UTC, stoimenov95 approved these changes

2024-04-21 18:54 UTC, merged