#159 improve notification component
learnhubmkd/app pull request #164
Opened 2024-04-15 23:00 UTC by Mikivitkovski

2024-04-16 17:46 UTC, edichoska approved these changes
@Mikivitkovski  this looks great! Lets wait for the captcha PR to be approved first.

2024-04-16 20:27 UTC, stoimenov95 approved these changes
Regarding the notification - everything looks great Miki!
However, I am not sure why is the Captcha code in this PR, but you can acknowledge the comments I left here and resolve them in the Captcha ticket.

2024-04-16 20:27 UTC, stoimenov95 commented on components/reusable-components/turnstile-captcha/CaptchaWidget.tsx
> +  siteKey = '0x4AAAAAAAWq36_j09RgOKQR',
We can keep this in some `.env` file.

2024-04-16 20:27 UTC, stoimenov95 commented on components/reusable-components/turnstile-captcha/CaptchaWidget.tsx
> +      script.src = 'https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';
This value can be kept in `.env` as well.

2024-04-18 08:26 UTC, edichoska commented
@Mikivitkovski merge this when you have he chance 🍀

2024-04-18 22:36 UTC, dichoska requested changes
we are closing this PR since Miki already created another one which contained only the changes in the notification component

2024-04-18 22:38 UTC, closed without merging