#181 - created reusable button component
learnhubmkd/app pull request #189
Opened 2024-04-22 10:11 UTC by kire21

-  changed existing button component

![Screenshot from 2024-04-22 12-09-09](https://github.com/learnhubmkd/app/assets/58231146/b9fcfb97-0880-405b-95c0-ef3e8323ecd3)

2024-04-22 20:28 UTC, edichoska commented on components/reusable-components/button/button.module.scss
> +  padding: 8px 24px 8px 24px;
padding: 8px 24px

2024-04-22 20:29 UTC, edichoska commented on components/reusable-components/button/button.module.scss
> +  padding: 8px 24px 8px 24px;
same here, we can maybe have one class for the styles that both buttons share, and the primary button would have the .primaryButton for the styles that are unique to the primaryButton. same for secondary button

2024-04-22 21:53 UTC, stoimenov95 requested changes
Please resolve the comments. Everything else seems great.

2024-04-23 11:06 UTC, kire21 commented
![Screenshot from 2024-04-23 11-49-37](https://github.com/learnhubmkd/app/assets/58231146/c0d86b73-2205-4957-a6f0-60128dc1a06f)

![Screenshot from 2024-04-23 11-49-11](https://github.com/learnhubmkd/app/assets/58231146/1029ec8f-897c-4513-ae42-c3308cb5640c)

![Screenshot from 2024-04-23 11-49-05](https://github.com/learnhubmkd/app/assets/58231146/6b26ab28-b6fe-492e-b7e4-f7414deb45a1)

![Screenshot from 2024-04-23 11-48-53](https://github.com/learnhubmkd/app/assets/58231146/d83fc189-27cd-422a-8f5e-24086a7ab7e6)

2024-04-23 20:43 UTC, stoimenov95 approved these changes

2024-04-23 20:43 UTC, stoimenov95 commented on app/page.module.scss
> +  // padding: 6rem;
Please remove unused comment.

2024-04-23 21:00 UTC, stoimenov95 approved these changes

2024-04-23 21:00 UTC, edichoska approved these changes
👏

2024-04-23 21:01 UTC, merged