improved theme toggle - detecting theme #186
learnhubmkd/app pull request #228
Opened 2024-05-09 10:55 UTC by ninman27

Created themeDetector function for detecting dark/light theme used in themeContext.

2024-05-09 11:26 UTC, RevanchistX requested changes
LGTM, just make the small change I requested

2024-05-09 11:26 UTC, RevanchistX commented on utils/themeDetector.ts
> +  const mListener = (e: any) => {
use descriptive names for variables

2024-05-14 12:39 UTC, ninman27 commented on utils/themeDetector.ts
> +  const mListener = (e: any) => {
The names of variables are changed.

2024-05-14 15:27 UTC, edichoska approved these changes

2024-05-14 15:28 UTC, merged